// src/lib/components/browse/GenreDrillPage.svelte
<script lang="ts">
  import { untrack }             from "svelte";
  import { tsunagu }             from "$lib/server-adapters/tsunagu";
  import { settingsState }       from "$lib/state/settings.svelte";
  import { setPreviewManga }     from "$lib/state/series.svelte";
  import { dedupeMangaById, shouldHideNsfw } from "$lib/core/util";
  import Thumbnail               from "$lib/components/shared/manga/Thumbnail.svelte";
  import ContextMenu             from "$lib/components/shared/ui/ContextMenu.svelte";
  import { ArrowLeftIcon, BookmarkSimpleIcon, CircleNotchIcon } from "phosphor-svelte";
  import type { Manga, Source }  from "$lib/types";
  import { toBrowseManga, toSource } from "$lib/components/browse/lib/searchFilter";
  import {
    PAGE_SIZE, INITIAL_PAGES, MAX_SOURCES,
    parseTags, tagsLabel, matchesAllTags, runConcurrent,
  } from "$lib/components/browse/lib/searchFilter";

  interface MenuItem {
    label:      string;
    icon?:      any;
    onClick:    () => void;
    danger?:    boolean;
    disabled?:  boolean;
    separator?: never;
    children?:  MenuEntry[];
  }
  interface MenuSeparator { separator: true }
  type MenuEntry = MenuItem | MenuSeparator;

  interface Props {
    genre:  string;
    onBack: () => void;
  }
  let { genre, onBack }: Props = $props();

  const tags       = $derived(parseTags(genre));
  const primaryTag = $derived(tags[0] ?? "");
  const label      = $derived(tagsLabel(tags));

  let libraryManga: Manga[]  = $state([]);
  let sourceManga:  Manga[]  = $state([]);
  let loadingInitial         = $state(true);
  let loadingMore            = $state(false);
  let visibleCount           = $state(PAGE_SIZE);
  let ctx: { x: number; y: number; manga: Manga } | null = $state(null);

  const nextPageMap = new Map<string, number>();
  let sources: Source[]                  = $state([]);
  let abortCtrl: AbortController | null = null;

  const filtered = $derived.by(() => {
    const libMatches = libraryManga.filter((m) => matchesAllTags(m, tags) && !shouldHideNsfw(m as any, settingsState.settings));
    const libIds     = new Set(libMatches.map((m) => m.id));
    return dedupeMangaById([...libMatches, ...sourceManga.filter((m) => !libIds.has(m.id) && !shouldHideNsfw(m as any, settingsState.settings))]);
  });

  const visibleItems   = $derived(filtered.slice(0, visibleCount));
  const hasMoreVisible = $derived(visibleCount < filtered.length);
  const hasMoreNetwork = $derived(sources.some((s) => (nextPageMap.get(s.id) ?? -1) > 0));
  const hasMore        = $derived(hasMoreVisible || hasMoreNetwork);

  $effect(() => { const f = genre; if (f) untrack(() => load(f)); });

  async function load(filter: string) {
    abortCtrl?.abort();
    const ctrl = new AbortController();
    abortCtrl  = ctrl;
    loadingInitial = true;
    sourceManga    = [];
    libraryManga   = [];
    visibleCount   = PAGE_SIZE;
    nextPageMap.clear();

    const t  = parseTags(filter);
    const pt = t[0] ?? "";

    tsunagu.library().then((entries) => {
      if (ctrl.signal.aborted) return;
      libraryManga = entries.map((e) => ({
        id:            e.id,
        title:         e.title,
        thumbnailUrl:  e.thumbnailUrl ?? "",
        inLibrary:     true,
        unreadCount:   e.unreadCount,
        downloadCount: e.downloadCount,
        genre:         e.genres,
        status:        e.status,
        source:        e.source ? { id: e.source.id, name: e.source.name, displayName: e.source.displayName, isNsfw: e.source.isNsfw } : null,
      }));
    }).catch(() => {});

    tsunagu.installedExtensions().then(async (exts) => {
      if (ctrl.signal.aborted) return;
      const srcs = exts.filter((e) => e.installed).map(toSource).slice(0, MAX_SOURCES);
      sources    = srcs;
      for (const src of srcs) nextPageMap.set(src.id, -1);

      await runConcurrent(srcs, async (src) => {
        if (ctrl.signal.aborted) return;
        const pageItems: Manga[] = [];
        for (let page = 1; page <= INITIAL_PAGES; page++) {
          if (ctrl.signal.aborted) return;
          let result: Awaited<ReturnType<typeof tsunagu.search>> | null = null;
          try {
            result = await tsunagu.search(src.id, pt, page, undefined, ctrl.signal);
          } catch { break; }
          if (!result || ctrl.signal.aborted) break;
          const mapped = result.results.map((r) => toBrowseManga(r, src.id));
          pageItems.push(...mapped);
          if (!result.hasNextPage) { nextPageMap.set(src.id, -1); break; }
          else if (page === INITIAL_PAGES) nextPageMap.set(src.id, INITIAL_PAGES + 1);
        }
        if (!ctrl.signal.aborted && pageItems.length > 0) {
          sourceManga    = dedupeMangaById([...sourceManga, ...pageItems]);
          loadingInitial = false;
        }
      }, ctrl.signal);

      if (!ctrl.signal.aborted) loadingInitial = false;
    }).catch(() => { if (!ctrl.signal.aborted) loadingInitial = false; });
  }

  async function loadMore() {
    if (loadingMore) return;
    if (hasMoreVisible) { visibleCount += PAGE_SIZE; return; }
    const srcs = sources.filter((s) => (nextPageMap.get(s.id) ?? -1) > 0);
    if (!srcs.length) return;
    loadingMore = true;
    abortCtrl?.abort();
    const ctrl = new AbortController();
    abortCtrl  = ctrl;
    try {
      await runConcurrent(srcs, async (src) => {
        const page = nextPageMap.get(src.id)!;
        if (ctrl.signal.aborted) return;
        let result: Awaited<ReturnType<typeof tsunagu.search>> | null = null;
        try {
          result = await tsunagu.search(src.id, primaryTag, page, undefined, ctrl.signal);
        } catch { nextPageMap.set(src.id, -1); return; }
        if (!result || ctrl.signal.aborted) return;
        nextPageMap.set(src.id, result.hasNextPage ? page + 1 : -1);
        const mapped = result.results.map((r) => toBrowseManga(r, src.id));
        if (mapped.length > 0) sourceManga = dedupeMangaById([...sourceManga, ...mapped]);
      }, ctrl.signal);
    } finally {
      if (!ctrl.signal.aborted) { visibleCount += PAGE_SIZE; loadingMore = false; }
    }
  }

  function openCtx(e: MouseEvent, m: Manga) {
    e.preventDefault();
    ctx = { x: e.clientX, y: e.clientY, manga: m };
  }

  function buildCtxItems(m: Manga): MenuEntry[] {
    return [
      {
        label: m.inLibrary ? "In Library" : "Add to library",
        icon: BookmarkSimpleIcon,
        disabled: m.inLibrary,
        onClick: () => tsunagu.addToLibrary(m.id)
          .then(() => { sourceManga = sourceManga.map((x) => x.id === m.id ? { ...x, inLibrary: true } : x); })
          .catch(console.error),
      },
    ];
  }

  $effect(() => () => { abortCtrl?.abort(); });
</script>

<div class="root">
  <div class="header">
    <button class="back" onclick={onBack}>
      <ArrowLeftIcon size={13} weight="light" /><span>Back</span>
    </button>
    <span class="title">{label}</span>
    {#if !loadingInitial || filtered.length > 0}
      <span class="result-count">{visibleItems.length}{filtered.length > visibleCount ? "+" : ""} of {filtered.length}</span>
    {/if}
    {#if !loadingInitial && hasMoreNetwork}
      <span class="loading-hint">More loading…</span>
    {/if}
  </div>

  {#if loadingInitial && filtered.length === 0}
    <div class="grid">
      {#each Array(50) as _}
        <div class="card-skeleton">
          <div class="cover-skeleton skeleton"></div>
          <div class="title-skeleton skeleton"></div>
        </div>
      {/each}
    </div>
  {:else if filtered.length === 0}
    <div class="empty">No manga found for "{label}".</div>
  {:else}
    <div class="grid">
      {#each visibleItems as m, i (`${m.extensionId}-${m.sourceEntryId}`)}
        <button class="card" onclick={() => setPreviewManga(m)} oncontextmenu={(e) => { e.stopPropagation(); openCtx(e, m); }}>
          <div class="cover-wrap">
            <Thumbnail src={m.thumbnailUrl} alt={m.title} class="cover" priority={i < 12 ? 12 - i : 0} id={m.id} />
            {#if m.inLibrary}<span class="in-library-badge">Saved</span>{/if}
          </div>
          <p class="card-title">{m.title}</p>
        </button>
      {/each}
      {#if hasMore}
        <div class="show-more-cell">
          <button class="show-more-btn" onclick={loadMore} disabled={loadingMore}>
            {#if loadingMore}<CircleNotchIcon size={13} weight="light" class="anim-spin" /> Loading…{:else}Show more{/if}
          </button>
        </div>
      {/if}
    </div>
  {/if}
</div>

{#if ctx}
  <ContextMenu x={ctx.x} y={ctx.y} items={buildCtxItems(ctx.manga)} onClose={() => ctx = null} />
{/if}

<style>
  .root { display: flex; flex-direction: column; height: 100%; overflow: hidden; animation: fadeIn 0.14s ease both; }
  .header { display: flex; align-items: center; gap: var(--sp-3); padding: var(--sp-4) var(--sp-6); border-bottom: 1px solid var(--border-dim); flex-shrink: 0; }
  .back { display: flex; align-items: center; gap: var(--sp-2); color: var(--text-muted); font-size: var(--text-xs); font-family: var(--font-ui); letter-spacing: var(--tracking-wide); text-transform: uppercase; background: none; border: none; cursor: pointer; padding: 0; transition: color var(--t-base); flex-shrink: 0; }
  .back:hover { color: var(--text-secondary); }
  .title { font-size: var(--text-base); font-weight: var(--weight-medium); color: var(--text-secondary); letter-spacing: var(--tracking-tight); }
  .result-count, .loading-hint { margin-left: auto; font-family: var(--font-ui); font-size: var(--text-2xs); color: var(--text-faint); letter-spacing: var(--tracking-wide); }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(clamp(100px,13vw,140px),1fr)); gap: var(--sp-4); padding: var(--sp-5) var(--sp-6) var(--sp-6); overflow-y: auto; flex: 1; align-content: start; will-change: scroll-position; -webkit-overflow-scrolling: touch; contain: layout style; }
  .card { background: none; border: none; padding: 0; cursor: pointer; text-align: left; }
  .card:hover :global(.cover) { filter: brightness(1.06); }
  .card:hover .card-title { color: var(--text-primary); }
  .cover-wrap { position: relative; aspect-ratio: 2/3; overflow: hidden; border-radius: var(--radius-md); background: var(--bg-raised); border: 1px solid var(--border-dim); transform: translateZ(0); }
  :global(.cover) { width: 100%; height: 100%; object-fit: cover; transition: filter var(--t-base); will-change: filter; }
  .in-library-badge { position: absolute; bottom: var(--sp-1); left: var(--sp-1); font-family: var(--font-ui); font-size: var(--text-2xs); letter-spacing: var(--tracking-wide); text-transform: uppercase; background: var(--accent-muted); color: var(--accent-fg); border: 1px solid var(--accent-dim); padding: 2px 5px; border-radius: var(--radius-sm); }
  .card-title { margin-top: var(--sp-2); font-size: var(--text-sm); color: var(--text-secondary); line-height: var(--leading-snug); display: -webkit-box; -webkit-line-clamp: 2; line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; transition: color var(--t-base); }
  .card-skeleton { padding: 0; }
  .cover-skeleton { aspect-ratio: 2/3; border-radius: var(--radius-md); }
  .title-skeleton { height: 11px; margin-top: var(--sp-2); width: 75%; }
  @keyframes shimmer { from { background-position: -200% 0 } to { background-position: 200% 0 } }
  .skeleton { border-radius: var(--radius-sm); background: linear-gradient(90deg, var(--bg-raised) 25%, var(--bg-overlay, color-mix(in srgb, var(--bg-raised) 80%, var(--text-primary) 6%)) 50%, var(--bg-raised) 75%); background-size: 200% 100%; animation: shimmer 1.6s ease-in-out infinite; }
  .empty { display: flex; align-items: center; justify-content: center; flex: 1; color: var(--text-faint); font-family: var(--font-ui); font-size: var(--text-xs); letter-spacing: var(--tracking-wide); }
  .show-more-cell { grid-column: 1/-1; display: flex; justify-content: center; padding: var(--sp-2) 0 var(--sp-4); }
  .show-more-btn { display: flex; align-items: center; gap: var(--sp-2); font-family: var(--font-ui); font-size: var(--text-xs); letter-spacing: var(--tracking-wide); padding: 7px 20px; border-radius: var(--radius-md); background: var(--bg-raised); color: var(--text-muted); border: 1px solid var(--border-dim); cursor: pointer; transition: color var(--t-base), border-color var(--t-base); }
  .show-more-btn:hover:not(:disabled) { color: var(--text-secondary); border-color: var(--border-strong); }
  .show-more-btn:disabled { opacity: 0.5; cursor: default; }
  @keyframes fadeIn { from { opacity: 0 } to { opacity: 1 } }
</style>

// src/components/explore/GenreDrillPage.tsx
import { useEffect, useState, useMemo, useRef, memo, useCallback } from "react";
import { ArrowLeft, BookmarkSimple, FolderSimplePlus, Folder, CircleNotch } from "@phosphor-icons/react";
import { gql, thumbUrl } from "../../lib/client";
import { GET_ALL_MANGA, GET_LIBRARY, GET_SOURCES, FETCH_SOURCE_MANGA, UPDATE_MANGA } from "../../lib/queries";
import { cache, CACHE_KEYS } from "../../lib/cache";
import { dedupeSources, dedupeMangaById } from "../../lib/sourceUtils";
import { useStore } from "../../store";
import ContextMenu, { type ContextMenuEntry } from "../context/ContextMenu";
import type { Manga, Source } from "../../lib/types";
import s from "./GenreDrillPage.module.css";

// ── Constants ──────────────────────────────────────────────────────────────────
const PAGE_SIZE         = 50;   // how many items to show at once
const INITIAL_PAGES     = 3;    // source API pages to fetch upfront per source
const MAX_SOURCES       = 12;   // max sources to query concurrently
const CONCURRENCY       = 4;    // parallel source fetches

async function runConcurrent<T>(
  items: T[],
  fn: (item: T) => Promise<void>,
  signal: AbortSignal,
): Promise<void> {
  let i = 0;
  async function worker() {
    while (i < items.length) {
      if (signal.aborted) return;
      const item = items[i++];
      await fn(item).catch(() => {});
    }
  }
  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, items.length) }, worker));
}

// ── CoverImg ──────────────────────────────────────────────────────────────────
const CoverImg = memo(function CoverImg({ src, alt, className }: { src: string; alt: string; className?: string }) {
  const [loaded, setLoaded] = useState(false);
  return (
    <img
      src={src} alt={alt} className={className}
      loading="lazy" decoding="async"
      onLoad={() => setLoaded(true)}
      style={{ opacity: loaded ? 1 : 0, transition: loaded ? "opacity 0.15s ease" : "none" }}
    />
  );
});

// ── GenreDrillPage ────────────────────────────────────────────────────────────
export default function GenreDrillPage() {
  const genre               = useStore((st) => st.genreFilter);
  const setGenreFilter      = useStore((st) => st.setGenreFilter);
  const setPreviewManga     = useStore((st) => st.setPreviewManga);
  const settings            = useStore((st) => st.settings);
  const folders             = useStore((st) => st.settings.folders);
  const addFolder           = useStore((st) => st.addFolder);
  const assignMangaToFolder = useStore((st) => st.assignMangaToFolder);

  const [libraryManga, setLibraryManga]     = useState<Manga[]>([]);
  const [sourceManga, setSourceManga]       = useState<Manga[]>([]);
  const [loadingInitial, setLoadingInitial] = useState(true);
  const [loadingMore, setLoadingMore]       = useState(false);
  const [visibleCount, setVisibleCount]     = useState(PAGE_SIZE);
  const [ctx, setCtx] = useState<{ x: number; y: number; manga: Manga } | null>(null);

  // Per-source next-page tracker; -1 means exhausted
  const nextPageRef  = useRef<Map<string, number>>(new Map());
  const sourcesRef   = useRef<Source[]>([]);
  const abortRef     = useRef<AbortController | null>(null);

  useEffect(() => {
    if (!genre) return;

    abortRef.current?.abort();
    const ctrl = new AbortController();
    abortRef.current = ctrl;

    setLoadingInitial(true);
    setSourceManga([]);
    setLibraryManga([]);
    setVisibleCount(PAGE_SIZE);
    nextPageRef.current = new Map();

    const preferredLang = settings.preferredExtensionLang || "en";

    // ── Library (fire-and-forget, doesn't block skeleton removal) ─────────
    cache.get(CACHE_KEYS.LIBRARY, () =>
      Promise.all([
        gql<{ mangas: { nodes: Manga[] } }>(GET_ALL_MANGA),
        gql<{ mangas: { nodes: Manga[] } }>(GET_LIBRARY),
      ]).then(([all, lib]) => {
        const libMap = new Map(lib.mangas.nodes.map((m) => [m.id, m]));
        return all.mangas.nodes.map((m) => libMap.get(m.id) ?? m);
      })
    )
    .then((manga) => { if (!ctrl.signal.aborted) setLibraryManga(manga); })
    .catch((e) => { if (e?.name !== "AbortError") console.error(e); });

    // ── Sources: stream results in as each source responds ────────────────
    cache.get(CACHE_KEYS.SOURCES, () =>
      gql<{ sources: { nodes: Source[] } }>(GET_SOURCES)
        .then((d) => dedupeSources(d.sources.nodes.filter((s) => s.id !== "0"), preferredLang))
    ).then(async (allSources) => {
      const sources = allSources.slice(0, MAX_SOURCES);
      sourcesRef.current = sources;
      // Start all sources at -1 (unknown/exhausted); the fetch loop will set the correct next page
      for (const src of sources) nextPageRef.current.set(src.id, -1);

      await runConcurrent(sources, async (src) => {
        if (ctrl.signal.aborted) return;
        const pageItems: Manga[] = [];
        for (let page = 1; page <= INITIAL_PAGES; page++) {
          if (ctrl.signal.aborted) return;
          try {
            const d = await gql<{ fetchSourceManga: { mangas: Manga[]; hasNextPage: boolean } }>(
              FETCH_SOURCE_MANGA,
              { source: src.id, type: "SEARCH", page, query: genre },
              ctrl.signal,
            );
            pageItems.push(...d.fetchSourceManga.mangas);
            if (!d.fetchSourceManga.hasNextPage) {
              nextPageRef.current.set(src.id, -1);
              break;
            } else if (page === INITIAL_PAGES) {
              // Has more pages beyond what we fetched upfront — mark for "load more"
              nextPageRef.current.set(src.id, INITIAL_PAGES + 1);
            }
          } catch (e: any) {
            if (e?.name === "AbortError") return;
            nextPageRef.current.set(src.id, -1);
            break;
          }
        }
        if (!ctrl.signal.aborted && pageItems.length > 0) {
          // Dedupe by ID only — title dedup across sources is too aggressive and collapses
          // legitimate different-source results that share a common title (e.g. "Action" genre)
          setSourceManga((prev) => dedupeMangaById([...prev, ...pageItems]));
          // Drop the skeleton as soon as we have anything
          setLoadingInitial(false);
        }
      }, ctrl.signal);

      if (!ctrl.signal.aborted) setLoadingInitial(false);
    }).catch((e) => {
      if (e?.name !== "AbortError") console.error(e);
      if (!ctrl.signal.aborted) setLoadingInitial(false);
    });

    return () => { ctrl.abort(); };
  }, [genre]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Derived merged list ────────────────────────────────────────────────────
  const filtered = useMemo(() => {
    const libMatches = libraryManga.filter((m) => (m.genre ?? []).includes(genre));
    const libIds = new Set(libMatches.map((m) => m.id));
    const srcAll = sourceManga.filter((m) => !libIds.has(m.id));
    return dedupeMangaById([...libMatches, ...srcAll]);
  }, [libraryManga, sourceManga, genre]);

  // ── Load more ──────────────────────────────────────────────────────────────
  const hasMoreVisible  = visibleCount < filtered.length;
  const hasMoreNetwork  = sourcesRef.current.some((src) => (nextPageRef.current.get(src.id) ?? -1) > 0);
  const hasMore         = hasMoreVisible || hasMoreNetwork;

  const loadMore = useCallback(async () => {
    if (loadingMore) return;

    // If there are buffered results, just reveal the next page
    if (hasMoreVisible) {
      setVisibleCount((v) => v + PAGE_SIZE);
      return;
    }

    // Fetch next pages from network
    const sources = sourcesRef.current.filter(
      (src) => (nextPageRef.current.get(src.id) ?? -1) > 0
    );
    if (!sources.length) return;

    setLoadingMore(true);
    abortRef.current?.abort();
    const ctrl = new AbortController();
    abortRef.current = ctrl;

    try {
      await runConcurrent(sources, async (src) => {
        const page = nextPageRef.current.get(src.id)!;
        if (ctrl.signal.aborted) return;
        try {
          const d = await gql<{ fetchSourceManga: { mangas: Manga[]; hasNextPage: boolean } }>(
            FETCH_SOURCE_MANGA,
            { source: src.id, type: "SEARCH", page, query: genre },
            ctrl.signal,
          );
          nextPageRef.current.set(src.id, d.fetchSourceManga.hasNextPage ? page + 1 : -1);
          if (!ctrl.signal.aborted && d.fetchSourceManga.mangas.length > 0)
            setSourceManga((prev) => dedupeMangaById([...prev, ...d.fetchSourceManga.mangas]));
        } catch (e: any) {
          if (e?.name !== "AbortError") nextPageRef.current.set(src.id, -1);
        }
      }, ctrl.signal);
    } finally {
      if (!ctrl.signal.aborted) {
        setVisibleCount((v) => v + PAGE_SIZE);
        setLoadingMore(false);
      }
    }
  }, [loadingMore, hasMoreVisible, genre]);

  // ── Context menu ──────────────────────────────────────────────────────────
  function openCtx(e: React.MouseEvent, m: Manga) {
    e.preventDefault(); e.stopPropagation();
    setCtx({ x: e.clientX, y: e.clientY, manga: m });
  }

  function buildCtxItems(m: Manga): ContextMenuEntry[] {
    return [
      {
        label: m.inLibrary ? "In Library" : "Add to library",
        icon: <BookmarkSimple size={13} weight={m.inLibrary ? "fill" : "light"} />,
        disabled: m.inLibrary,
        onClick: () => gql(UPDATE_MANGA, { id: m.id, inLibrary: true })
          .then(() => {
            setSourceManga((prev) => prev.map((x) => x.id === m.id ? { ...x, inLibrary: true } : x));
            cache.clear(CACHE_KEYS.LIBRARY);
          })
          .catch(console.error),
      },
      ...(folders.length > 0 ? [
        { separator: true } as ContextMenuEntry,
        ...folders.map((f): ContextMenuEntry => ({
          label: f.mangaIds.includes(m.id) ? `✓ ${f.name}` : f.name,
          icon: <Folder size={13} weight={f.mangaIds.includes(m.id) ? "fill" : "light"} />,
          onClick: () => assignMangaToFolder(f.id, m.id),
        })),
      ] : []),
      { separator: true },
      {
        label: "New folder & add",
        icon: <FolderSimplePlus size={13} weight="light" />,
        onClick: () => {
          const name = prompt("Folder name:");
          if (name?.trim()) { const id = addFolder(name.trim()); assignMangaToFolder(id, m.id); }
        },
      },
    ];
  }

  const visibleItems = filtered.slice(0, visibleCount);

  return (
    <div className={s.root}>
      <div className={s.header}>
        <button className={s.back} onClick={() => setGenreFilter("")}>
          <ArrowLeft size={13} weight="light" />
          <span>Back</span>
        </button>
        <span className={s.title}>{genre}</span>
        {loadingInitial && filtered.length === 0 ? null : (
          <span className={s.resultCount}>
            {visibleItems.length}{filtered.length > visibleCount ? "+" : ""} of {filtered.length}
          </span>
        )}
        {!loadingInitial && hasMoreNetwork && (
          <span className={s.loadingHint}>More loading…</span>
        )}
      </div>

      {loadingInitial && filtered.length === 0 ? (
        <div className={s.grid}>
          {Array.from({ length: 50 }).map((_, i) => (
            <div key={i} className={s.cardSkeleton}>
              <div className={["skeleton", s.coverSkeleton].join(" ")} />
              <div className={["skeleton", s.titleSkeleton].join(" ")} />
            </div>
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <div className={s.empty}>No manga found for "{genre}".</div>
      ) : (
        <div className={s.grid}>
          {visibleItems.map((m) => (
            <button key={m.id} className={s.card} onClick={() => setPreviewManga(m)} onContextMenu={(e) => openCtx(e, m)}>
              <div className={s.coverWrap}>
                <CoverImg src={thumbUrl(m.thumbnailUrl)} alt={m.title} className={s.cover} />
                {m.inLibrary && <span className={s.inLibraryBadge}>Saved</span>}
              </div>
              <p className={s.cardTitle}>{m.title}</p>
            </button>
          ))}
          {hasMore && (
            <div className={s.showMoreCell}>
              <button className={s.showMoreBtn} onClick={loadMore} disabled={loadingMore}>
                {loadingMore
                  ? <><CircleNotch size={13} weight="light" className="anim-spin" style={{ display:"inline-block" }} /> Loading…</>
                  : `Show more`}
              </button>
            </div>
          )}
        </div>
      )}

      {ctx && (
        <ContextMenu x={ctx.x} y={ctx.y} items={buildCtxItems(ctx.manga)} onClose={() => setCtx(null)} />
      )}
    </div>
  );
}
